### 벡터 - Vectors

* 벡터는 벡터 공간의 원소를 벡터라 하며, 
* 백터들은 서로 더하거나 스칼라에 의해 곱해질 수 있다.
* 벡터를 숫자들의 리스트라고 생각해 보자.
  * 예)

In [44]:
height_weigth_age = [70,    # inches
                    170,    # pounds
                    40 ]    # years

In [45]:
grades = [95,    # exam1
          80,    # exam2
          75,    # exam3
          62 ]   # exam4

* Python의 list는 벡터 연산을 제공하지 않기 때문에, 벡터 연산을 추가해 보자.

### 벡터 합과 차

* 원소별로 계산 : 다음을 구현하고 싶음
  * [1, 2] 더하기 [3, 4] = [4, 6]
  * [5, 3] 빼기 [1, 7] = [4, -4]

In [1]:
def vector_add(v, w):
    """adds two vectors componentwise"""
    return [v_i + w_i for v_i, w_i in zip(v,w)]

In [2]:
def vector_subtract(v, w):
    """subtracts two vectors componentwise"""
    return [v_i - w_i for v_i, w_i in zip(v,w)]

### 여러 개의 벡터들의 합

* 벡터들의 리스트가 있을 때, 리스트 내의 벡터들을 원소 별로 합하기

In [3]:
def vector_sum(vectors):
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_add(result, vector)
    return result

In [4]:
def vector_sum(vectors):
    return reduce(vector_add, vectors)

### 스칼라 곱

* 목표 : 3*[1, 2, 3] = [3, 6, 9]

In [5]:
def scalar_multiply(c, v):
    return [c* vi for vi in v]

* 컴포넌트별 평균 : vector_mean([1,2],[2,4],[3,6]) == [3,6] 

In [6]:
def vector_mean(vectors):
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

* 단, 위의 나누기에 실수 나누기를 적용하기 위해서는 파일 위쪽에 다음을 표기

In [7]:
from __future__ import division

### dot product

* 목표 : 
  * dot( [1, 2, 3], [0, 1, 2]) = sum([1*0, 2*1, 3*2]) 
    = sum([0, 2, 6]) = 8

In [8]:
def dot(v, w):
    """v_1 * w_1 + ... + v_n * w_n"""
    return sum(v_i * w_i for v_i, w_i in zip(v, w))

### 제곱합

* 벡터 원소들의 제곱의 합

In [9]:
def sum_of_squares(v):
    """v_1 * v_1 + ... + v_n * v_n"""
    return dot(v, v)

* 벡터의 크기(magnitude) : 제곱합의 제곱근

In [10]:
import math
def magnitude(v):
    return math.sqrt(sum_of_squares(v))

### 벡터 사이의 거리

* 한 벡터에서 다른 벡터를 뺀 후, 크기를 구하는 것과 동일

In [12]:
def distance(v, w):
   return magnitude(vector_subtract(v, w))

### NumPy

* numpy 라이브러리에는 지금까지 행한 벡터 연산들이 구현되어 있음
* http://www.numpy.org/
  * 예)

In [46]:
# dot product
import numpy as np
np.dot([1,2], [3,4])

11

### Numpy array 

* 다차원 배열을 구현
* 수학적 계산에 특화

In [13]:
import numpy as np
a = np.array([0, 1, 2, 3])

In [14]:
a.ndim  # 1 차원

1

In [15]:
a.shape  # 형태 : (4,)

(4L,)

In [16]:
len(a)  # 4

4

In [17]:
b = np.array([[0,1,2], [3,4,5]])

In [18]:
b.ndim  # 2차원

2

In [19]:
b.shape # 형태 (2,3)

(2L, 3L)

In [20]:
len(b)  # 2 : 첫번째 차원의 길이

2

### array 생성

In [22]:
a = np.arange(10)  # range 함수와 비슷

In [23]:
b = np.arange(1, 9, 2) 

In [24]:
c = np.linspace(0, 1, 6)  #시작, 끝, 숫자 개수

In [25]:
d = np.ones((3, 3))  # 1로 이루어진 다차원 배열

In [26]:
e = np.zeros((2, 2))  # 0으로 이루어진 다차원 배열

In [27]:
f = np.eye(3)  # identity 행렬

In [29]:
g = np.diag(np.array([1, 2, 3, 4]))  # 대각 행렬

### array 생성(2)

In [30]:
np.random.rand(4)       # uniform in [0, 1]

array([ 0.50653746,  0.71346939,  0.00128869,  0.35647507])

In [31]:
np.random.randn(4)      # standard normal

array([  1.81391703e-03,  -1.42263003e+00,   3.54962812e-01,
        -1.83870667e+00])

In [32]:
2.5 * np.random.randn(4) + 3   # 평균 3, 표준편차 2.5

array([ 3.45673421,  1.02806199,  1.80874561, -1.95053438])

* list로부터 array 만들기

In [33]:
x = [2, 3, 1, -1]
y = np.asarray(x)

### numpy와 numpy.linalg를 이용한 선형대수

* 벡터 합과 차

In [36]:
a = np.array([3,1,-1])
b = np.arange(3)
c = a + b
d = b - a

* 스칼라 곱

In [37]:
4*a

array([12,  4, -4])

* 제곱합

In [38]:
np.sum(a**2)

11

* dot product

In [39]:
np.dot(a, b)

-1

* 벡터 사이의 거리


In [40]:
np.linalg.norm(a-b)

4.2426406871192848

In [41]:
M = np.array([[1,2], [3,4]])

In [42]:
N = np.array([[-1,1],[2,1]])

* 역행렬

In [43]:
np.linalg.inv(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

* 행렬식

In [47]:
np.linalg.det(M)

-2.0000000000000004

* 해 찾기

In [48]:
c = np.array([2,1])
np.linalg.solve(M, c)

array([-3. ,  2.5])

* 행렬곱

In [49]:
np.matmul(M,N)

array([[3, 3],
       [5, 7]])